from typing import Union
from pydantic import BaseModel, Field

class Token(BaseModel):
    """
    Pydantic Token model used to deliver a JWT generated by the app.
    """
    access_token: str
    token_type: str

class UserIn(BaseModel):
    """
    Pydantic User model used to receive data about an user from the user.
    """
    username: str =  Field(min_length=1, max_length=50)
    password: str = Field(min_length=1, max_length=100)
    check_password:str = Field(min_length=1, max_length=100)

# class UserOut(BaseModel):
#     user_id: int
#     username: str
#     password: str

class ProjectIn(BaseModel):
    """
    Pydantic Project model used to receive data about a project from the user.
    """
    name: str = Field(min_length=1, max_length=50)
    description: Union[str, None] = Field(min_length=0, max_length=200)

class ProjectOut(BaseModel):
    """
    Pydantic Project model used to deliver data about a project to the user.
    """
    project_id: int
    name: str
    description: Union[str, None]
    owner: int

class DocumentIn(BaseModel):
    """
    Pydantic Document model used to receive data about a document from the user.
    """
    name: str = Field(min_length=1, max_length=50)
    file_url: str = Field(min_length=1, max_length=200)

class DocumentOut(BaseModel):
    """
    Pydantic Document model used to deliver data about a document to the user.
    """
    document_id: int
    name: str
    format: str
    file_url: str
    attached_project: int

