from typing import Annotated
from http import HTTPStatus
from fastapi import HTTPException, Depends
from fastapi.security import OAuth2PasswordBearer
from jwt.exceptions import InvalidTokenError
import jwt
from datetime import datetime, timedelta, timezone

import src.db.orm as db
from src.app.utils_db.session_singleton import SessionSingleton
from src.app.utils_db.utils_db_user.utils_db_user_impl import UtilsDbUserImpl

utils_db_user = UtilsDbUserImpl(SessionSingleton())

class Authenticator:

    # Setting for the JWT encoding.
    SECRET_KEY = '-SuP3R_s3Cr3T_K3Y*'
    ALGORITHM = 'HS256'
    ACCESS_TOKEN_EXPIRE_MINUTES = 60

    oauth2_scheme = OAuth2PasswordBearer(tokenUrl='login')
    @classmethod
    def create_token(cls, username:str) -> str:
        """
        Creates the JWT shared with the user,
        :param username: str who contains the username of the user to authenticate.
        :return: str with the encoded JWT token.
        """
        if cls.ACCESS_TOKEN_EXPIRE_MINUTES:
            expire = timedelta(minutes=cls.ACCESS_TOKEN_EXPIRE_MINUTES)
        else:
            expire = timedelta(minutes=5)
        expire += datetime.now(timezone.utc)
        data = {'sub': username, 'exp': expire}
        access_token = jwt.encode(data, cls.SECRET_KEY, algorithm=cls.ALGORITHM)
        return access_token

    @classmethod
    def authentication(cls, token: Annotated[str, Depends(oauth2_scheme)]) -> db.User:
        """
        Decodes a JWT generated by the app and validates it against the database to grant access.
        :param token: str containing the JWT generated by the app.
        :return: User object of the orm model related to the user who is trying to authenticate.
        """
        if token:
            try:
                payload = jwt.decode(token, cls.SECRET_KEY, algorithms=[cls.ALGORITHM])
                username = payload.get('sub')
                auth_user = utils_db_user.read_user_by_username(username)
                if auth_user:
                    return auth_user
                raise HTTPException(status_code=HTTPStatus.UNAUTHORIZED,
                    detail="No current platform access (the provided username doesn't match with our system), login again.",
                    headers={'WWW-Authenticate': 'Bearer'})
            except InvalidTokenError:
                raise HTTPException(status_code=HTTPStatus.UNAUTHORIZED,
                    detail="No current platform access You must provide a valid token, login again.",
                    headers={'WWW-Authenticate': 'Bearer'})
        raise HTTPException(status_code=HTTPStatus.UNAUTHORIZED,
                    detail="No current platform access. You must provide a valid token, login again.",
                    headers={'WWW-Authenticate': 'Bearer'})